version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - sche-network

  client:
    build: ./client
    ports:
      - "8888:80"
    depends_on:
      - server
    networks:
      - sche-network

networks:
  sche-network:
    driver: bridge